- name: Create node_exporter directories and set ownership
  hosts: localhost
  vars:
    APPNAME: "/node_exporter"
    PERMISSION_APPNAME: node_exporter
    BINARY: "{{ APPNAME }}/bin/"
    LOGFILE: "{{ APPNAME }}/logs/"

  tasks:
    - name: Create BINARY directory
      ansible.builtin.file:
        path: "{{ BINARY }}"
        state: directory
        recurse: true

    - name: Create LOGFILE directory
      ansible.builtin.file:
        path: "{{ LOGFILE }}"
        state: directory
        recurse: true

    - name: Change ownership of /node_exporter recursively
      ansible.builtin.file:
        path: "{{ APPNAME }}"
        owner: "{{ PERMISSION_APPNAME }}"
        group: "{{ PERMISSION_APPNAME }}"
        recurse: true
