- name: Configure node_exporter application directories and setup
  hosts: localhost
  gather_facts: false
  vars:
    APPNAME: "/node_exporter"
    PERMISSION_APPNAME: node_exporter
    BINARY: "{{ APPNAME }}/bin/"
    LOGFILE: "{{ APPNAME }}/logs/"
    NODE_EXPORTER_VERSION: "1.10.2"
    NODE_EXPORTER_ARCHIVE: "node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64.tar.gz"
    NODE_EXPORTER_URL: "https://github.com/prometheus/node_exporter/releases/download/v{{ NODE_EXPORTER_VERSION }}/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64.tar.gz"
    NODE_EXPORTER_ARCHIVE_DEST: "{{ BINARY }}/{{ NODE_EXPORTER_ARCHIVE }}"
    EXTRACTION_PATH: "{{ BINARY }}/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64"

  tasks:
    - name: Set permissions on bin directory
      ansible.builtin.file:
        path: "{{ BINARY }}"
        owner: "{{ PERMISSION_APPNAME }}"
        group: "{{ PERMISSION_APPNAME }}"
        recurse: true
        mode: '0750'

    - name: Set permissions on logs directory
      ansible.builtin.file:
        path: "{{ LOGFILE }}"
        owner: "{{ PERMISSION_APPNAME }}"
        group: "{{ PERMISSION_APPNAME }}"
        recurse: true
        mode: '0755'

    - name: Download node_exporter tarball
      ansible.builtin.get_url:
        url: "{{ NODE_EXPORTER_URL }}"
        dest: "{{ NODE_EXPORTER_ARCHIVE_DEST }}"
        mode: '0644'

    - name: Extract node_exporter tarball
      ansible.builtin.unarchive:
        src: "{{ NODE_EXPORTER_ARCHIVE_DEST }}"
        dest: "{{ BINARY }}"
        remote_src: true

    - name: Create symbolic link for node_exporter directory
      ansible.builtin.file:
        src: "{{ EXTRACTION_PATH }}"
        dest: "{{ BINARY }}/node_exporter"
        state: link
